---
- name: add nginx repo
  apt_repository: repo='{{ item }} http://nginx.org/packages/mainline/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release|lower }} nginx' state=present
  with_items:
    - deb
    - deb-src

- apt_key: url=http://nginx.org/packages/keys/nginx_signing.key

- name: install nginx
  apt: pkg=nginx state=latest update_cache=yes

- name: check if nginx exists
  stat: path=/etc/nginx
  register: nginx_path

- name: copy nginx.conf to /etc/nginx
  template:
    backup=no
    dest=/etc/nginx/nginx.conf
    src=nginx.conf.j2
    owner=root
    group=root
    mode=0644
  when: nginx_path.stat.exists
  notify:
    - restart nginx

- name: remove the default vhost
  file: path=/etc/nginx/conf.d/default.conf state=absent
  notify:
    - restart nginx

- name: include ssl config
  include: ssl.yml tags=ssl
  when: ssl_config == true
