---
- name: install redis-server
  apt: pkg=redis-server state=latest

- name: copy redis config
  template:
    src=redis.conf.j2
    dest=/etc/redis/redis.conf
    owner=root
    mode=0644
  tags:
    - config

- name: start redis
  service: name=redis-server state=restarted
